### ISSUE TITLE
Составить список основных сценариев по ролям

### ISSUE THREAD

**Issue by LeonovDS** [TangutCorpus/TangutSite#10]
Задача:

- Составить список сценариев взаимодействия с сайтом для каждой роли
- Оценить приоритет сценария. Определить, что входит в MVP
- Задокументировать в Wiki

**Comment by LeonovDS** [comment]
Блок: #8 
Задача: 
- Составить список сценариев взаимодействия с сайтом для каждой роли
- Оценить приоритет сценария. Определить, что входит в MVP

**Comment by LeonovDS** [comment]
#8 : роли

> Практически всё так.
> 
> * Посетитель: поиск, чтение.
> * Пользователь: ... + закладки, редактирование статей слов и текстов (комментарии — это дополнительные сведения о тексте или слове, которые не получается разбросать по другим категориям).
> * Модератор: ... + проверка правок, блокировка.
> * Админ: ... + привилегии, удаление статей (+ страниц пользователей и блокировки, но это уже не входит в MVP).

**Comment by witbore** [comment]
Посетитель:
- [ Посик иероглифа ]: Главная -> Поиск -> Иероглиф.
- [ Поиск перевода отрывка текста ]: Главная -> Поиск -> Строка.
- [ Поиск иероглифа из текста ]: Главная -> Поиск -> Строка -> Иероглиф.
- [ Поиск перевода текста ]: Главная -> Библиотека -> { Текст -> Иероглиф } -> { ... } -> ...
- [ Регистрация / Вход ]: Главная -> Регистрация / Вход -> Профиль. 

Пользователь:
- Всё то же.
- [ Переход из закладок ]: Главная -> Вход -> Профиль -> Закладки -> Иероглиф / Отрывок текста.
- [ Добавление в закладки ]: Главная -> Поиск -> Иероглиф / Строка / Текст + Добавление.
- [ Добавление иероглифа / текста ]: Главная -> Вход -> Страница редактора -> Страница модерации.
- [ Изменение иероглифа / текста ]: Главная -> Вход -> Поиск -> Страница иероглифа / текста -> Страница редактора -> Страница модерации.
- [ Проверка статуса статьи из списка правок ]: Главная -> Вход -> Профиль -> Список правок -> Страница модерации.

Модератор:
- Всё то же.
- [ Модерирование ]: Главная -> Вход -> Админка -> Список страниц на модерировании -> Страница модерации + Одобрение / Отклонение -> Страница иероглифа / текста или Список страниц на модерации.
- [ Блокировка пользователя из истории страницы ]: Главная -> Вход -> Страница -> Список редакторов -> Страница блокируемого + Блокировка -> Главная. _// Не думаю, что нужно хранить старые версии страниц, но имена пользователей и сколько байт изменено не должны занять много места._
- [ Блокировка пользователя ]: Главная -> Вход -> Админка -> Список пользователей для изменения привилегий + Блокировка.

Админ:
- Всё то же.
- [ Изменение привилегий ]: Главная -> Вход -> Админка -> Список пользователей для изменения привилегий + Изменение прав.
- [ Удаление статьи ]: Главная -> Вход -> Админка -> Список всех статей -> Поиск по всем статьям для удаления.
- [ Удаление определённых или всех статей пользователя ] Главная -> Вход -> Админка -> Список всех статей -> Поиск по отфильтрованым статьям для удаления.
- [ Удаление пользователя ]: Главная -> Вход -> Админка -> Список пользователей для изменения привилегий + Удаление.


Для MVP мы убираем Модератора и всё, кроме [ Изменение привилегий ] и [ Блокировка пользователя ], у Админа. У Пользователя "Страница модерации" ведёт сразу на статью, убираем [ Переход из закладок ] и [ Добавление в закладки ]. У Посетителя профиль неподтверждённый без прав Пользователя.
