### ISSUE TITLE
CJM: Поиск и чтение текста

### ISSUE THREAD

**Issue by LeonovDS** [TangutCorpus/TangutSite#13]
Тут нужно подумать о сценариях связанных с поиском и просмотром текстов/строк текстов. Как будет выглядеть поиск, по чему можно будет искать (иероглифы, переводы, источник, что-то еще), будут ли какие-то фильтры и сортировки. Дальше все это нарисовать в виде схемы см. #12

**Comment by LeonovDS** [comment]
https://github.com/TangutCorpus/TangutSite/wiki/CJM
Примерно тот формат cjm, который я ожидаю. Можно делать в wiki, через mermaid диаграммы, можно придумать что-то свое. Уровень счастья пользователя не обязателен. Главное - так же подробно расписать взаимодействие пользователя с сайтом с учетом различных крайних случаев. Цель - описать все настолько подробно, чтобы при разработке дизайна был на 100% понятен список интерактивных элементов, которые должны находиться в каждый момент времени на экране

**Comment by AlesHill** [comment]
1. Посетитель
Поиск перевода отрывка текста:
Посетитель, зайдя на главную страницу сайта, видит поисковую строку, в которой он может ввести интересующий его текст, фразу или отдельный иероглиф. После ввода запроса отображается страница с результатами, где выводится список строк текста, содержащих искомые слова или символы. В каждом результате показывается небольшой контекст с выделением найденного текста. Каждая строка является частью определённого текста, и посетитель может выбрать любую из них, чтобы перейти на страницу с полным текстом, включающим данную строку, и его переводом. На странице текста отображается оригинальный тангутский текст, перевод, а также дополнительные аннотации или комментарии, если таковые имеются.

Чтение текста из отрывка:
После выбора строки посетитель попадает на страницу полного текста, к которому она относится. На странице отображается полный текст с выделением выбранной строки, её переводом и дополнительными комментариями. Также может быть доступна возможность переключения между режимами отображения оригинала, перевода и параллельного представления.

Регистрация / Вход:
Посетитель, желающий получить доступ к дополнительным функциям сайта, нажимает на кнопку "Регистрация" или "Вход" на главной странице. Для регистрации он заполняет форму с указанием имени, электронной почты и пароля. После отправки формы и подтверждения регистрации он ожидает одобрения своей заявки от администратора. После получения одобрения пользователь получает доступ к расширенным функциям сайта. Если у посетителя уже есть учётная запись, он вводит свои данные для входа в систему.

2. Пользователь
Зарегистрированный пользователь обладает всеми возможностями посетителя, а также дополнительными функциями. Однако регистрация на сайте доступна только с одобрения администратора. Потенциальный пользователь может отправить запрос на регистрацию, указав свои данные, и дождаться решения администрации.

Добавление текста:
После входа в систему пользователь получает доступ к разделу редактора. Нажав на кнопку "Добавить текст", он переходит на страницу ввода текста. В специальной форме пользователь вводит текст на тангутском языке, указывает его перевод, при необходимости добавляет аннотации или примечания. После завершения работы текст сохраняется и становится доступным на сайте для других пользователей.

Изменение текста:
Для редактирования ранее добавленного текста пользователь может воспользоваться поисковой функцией или перейти к тексту через список своих публикаций. Открыв нужный текст, он нажимает на кнопку "Редактировать", после чего попадает в редактор. Здесь пользователь может внести изменения в оригинальный текст, его перевод или примечания. После завершения редактирования текст сохраняется и обновляется на сайте.

3. Администратор
Администратор имеет доступ ко всем функциям посетителей и пользователей, а также к административным инструментам управления сайтом.

Изменение привилегий:
После входа в систему администратор переходит в административную панель через доступную ему ссылку. В админке он открывает список всех зарегистрированных пользователей, где видит их текущие привилегии. Для изменения прав конкретного пользователя администратор выбирает его из списка, нажимает на кнопку "Изменить привилегии", выбирает новую роль (например, модератор) и сохраняет изменения.

Блокировка пользователя:
В админке администратор также имеет возможность заблокировать нарушителей. Найдя нужного пользователя в списке, он нажимает кнопку "Блокировать". После подтверждения блокировки пользователь теряет доступ к своему аккаунту и функциональности сайта.

Удаление статьи:
Администратор может удалить любой текст, опубликованный на сайте. Для этого он переходит в раздел со списком всех текстов, где доступен фильтр поиска по названию, автору или содержанию текста. Найдя нужный документ, администратор открывает его страницу и нажимает кнопку "Удалить текст". После подтверждения текст удаляется из базы данных и становится недоступным для всех пользователей.
