### ISSUE TITLE
Выбрать библиотеку компонентов

### ISSUE THREAD

**Issue by LeonovDS** [TangutCorpus/TangutSite#7]
Предлагаю взглянуть на [список библиотек компонентов](https://github.com/vuejs/awesome-vue?tab=readme-ov-file#components--libraries) и подобрать что-нибудь. Например, shadcn

**Comment by LeonovDS** [comment]
Я посмотрел, вот самые популярные варианты:
- https://vuetifyjs.com/en/resources/made-with-vuetify/ 
- https://quasar.dev/components
- https://www.shadcn-vue.com/examples/authentication.html
- https://buefy.org/expo
- https://primevue.org

На что надо обратить внимание: 
1. Насколько они подходят по дизайну / насколько все можно донастроить
2. Достаточно ли доступных компонентов (на первый взгляд)
3. Удобство использования (чисто пробежаться глазами по документации)
4. Наличие готовых компонентов для Figma (сильно ускорит разработку дизайна)

**Comment by LeonovDS** [comment]
Почему предлагаю готовые компоненты:
- Надо писать меньше кода для простых вещей 
- Меньше шансов запороть стили
- Проще делать дизайн
- Заранеее решены все проблемы с accessibility

**Comment by LeonovDS** [comment]
Если ничего не понравится, то вариант делать все своими руками остается. Но это займет больше времени

**Comment by noweretoGo** [comment]
> Предлагаю взглянуть на [список библиотек компонентов](https://github.com/vuejs/awesome-vue?tab=readme-ov-file#components--libraries) и подобрать что-нибудь. Например, shadcn

1) Ant Design Vue - интересные готовые элементы (мало готовых анимации)
2) Buefy - просто крутая библиотека
3) qui-max - интересный дизайн готовых элементов
4) Quasar - ну это quasar
5) Vexip UI - Есть интересные фишки
6) Shadcn UI - Много вариаций для анимации 
7) PrimeVue - куча полезных готовых элементов
8) Vuetify - крутые анимации 

На нумерацию не смотрите сделал ее просто так, все что я перечислил мне нравится и имеет большое количество готовых элементов которые можно быстро реализовать. 
Жду вашего решения какие будем оставлять.

@LeonovDS 
@angry-bun

**Comment by LeonovDS** [comment]
С моей колокольни:
-  смог найти официальные компоненты figma только для 6 и 8 (но искал с телефона, мб что-то упустил)
- у 7 они платные вроде как
- у 4 есть сторонняя реализация, мб у кого-то ещё тоже

**Comment by LeonovDS** [comment]
Пользуюсь правами диктатора и выбираю ShadCN. Пора начинать работать
https://www.shadcn-vue.com/docs/figma.html -- ссылка на страницу ссылкой на фигму, чтобы надергать оттуда компонентов)
