### ISSUE TITLE
Определить список ролей пользователей

### ISSUE THREAD

**Issue by LeonovDS** [TangutCorpus/TangutSite#8]

**Comment by LeonovDS** [comment]
Гипотеза:
- Читатель - чтение + комментарии
- Редактор - чтение + комментарии + добавление материалов
- Модератор - ... + одобрение или отклонение
- Админ - дроп базы данных, раздача привилегий

**Comment by witbore** [comment]
Практически всё так.
- Посетитель: поиск, чтение.
- Пользователь: ... + закладки, редактирование статей слов и текстов (комментарии — это дополнительные сведения о тексте или слове, которые не получается разбросать по другим категориям). 
- Модератор: ... + проверка правок, блокировка. 
- Админ: ... + привилегии, (удаление статей, страниц пользователей + блокировки).
